### ISSUE TITLE
Pete Goss or Peter Goss?

### ISSUE THREAD

**Issue by HughParsonage** [HughParsonage/grattanReporter#14]
Bio says:

> Dr Pete Goss has over 10 years’ experience as a strategy consultant, most recently with the Boston Consulting Group, advising Federal and State governments on service delivery innovation. 

and recent article https://grattan.edu.au/news/school-funding-circuit-breaker-with-appeal-to-all/

> by Pete Goss

but reports generally use `Peter`.

Can't have either or as this will muck up ibids in bibliography.

**Comment by HughParsonage** [comment]
@Cam-chisholm Please get to the bottom of this, but make sure your methods are orthodox.

**Comment by Cam-chisholm** [comment]
Can I just choose Peter and be done with it?

________________________________
