### ISSUE TITLE
Check space after \etc, etc.

### ISSUE THREAD

**Issue by Cam-chisholm** [HughParsonage/grattanReporter#8]

**Comment by HughParsonage** [comment]
I've forgotten what this means.

**Comment by Cam-chisholm** [comment]
Check to make sure \etc{} is used if a space is meant to follow.

**Comment by HughParsonage** [comment]
Ah to avoid `etcOh no I'm stuck to etc` while allowing `ie, this is fine`.

**Comment by Cam-chisholm** [comment]
Correct
